create table BILL_INFORMATION (ID integer not null auto_increment, AMOUNT float(7,2) not null, BILL_NUMBER varchar(50) not null, BILLING_DATE datetime not null, CUSTOMER_ID integer not null, PENDING_AMOUNT float(7,2), ORDER_ID integer not null, primary key (ID)) engine=InnoDB;
create table CUSTOMER (ID integer not null auto_increment, ADDRESS varchar(255), CREATED_ON datetime not null, NAME varchar(100) not null, PHONE_NUMBER varchar(15) not null, STATUS enum ('ACTIVE', 'INACTIVE') not null, primary key (ID)) engine=InnoDB;
create table DISTRIBUTOR (ID integer not null auto_increment, ADDRESS varchar(255), CREATED_ON datetime not null, NAME varchar(100) not null, PHONE_NUMBER varchar(15) not null, STATUS enum ('ACTIVE', 'INACTIVE') not null, primary key (ID)) engine=InnoDB;
create table ITEM (ID integer not null auto_increment, ADDED_ON datetime not null, ARCHIVE bit(1) default b'0', BASE_UNIT enum ('PC', 'BOX', 'BAG') not null, BASE_UNIT_PRICE float(7,2) not null, LARGE_UNIT enum ('PC', 'BOX', 'BAG') not null, LARGE_UNIT_IN_BASE_UNIT integer, LARGE_UNIT_PRICE float(7,2), MODIFIED_ON datetime, NAME varchar(100) not null, primary key (ID)) engine=InnoDB;
create table ORDER (ID integer not null auto_increment, CUSTOMER_ID integer not null, DESCRIPTION varchar(255), MODIFIED_ON datetime not null, ORDER_DATE datetime not null, ORDER_NUMBER varchar(50) not null, STATUS enum ('ACTIVE', 'INACTIVE') not null, primary key (ID)) engine=InnoDB;
create table ORDER_DETAIL (ID integer not null auto_increment, QUANTITY float(5,2) not null, UNIT enum ('PC', 'BOX', 'BAG') not null, ITEM_ID integer not null, ORDER_ID integer not null, primary key (ID)) engine=InnoDB;
create table PAYMENT_INFORMATION (ID integer not null auto_increment, AMOUNT float(7,2) not null, APPROVAL_DATE datetime, APPROVED bit not null, DESCRIPTION varchar(255), PAYMENT_DATE datetime, BILL_ID integer, primary key (ID)) engine=InnoDB;
alter table BILL_INFORMATION add constraint UK_funuve1egaw9nbp73ra474kyn unique (BILL_NUMBER);
alter table ORDER add constraint UK_57vbw9dfyibhhr6ry28ea8i5b unique (ORDER_NUMBER);
alter table BILL_INFORMATION add constraint FKsn94ae3mx25l2gjkjpw87cymf foreign key (ORDER_ID) references ORDER (ID);
alter table ORDER_DETAIL add constraint FKbe30jlhy5kaltqnmxgxs10p2w foreign key (ITEM_ID) references ITEM (ID);
alter table ORDER_DETAIL add constraint FKl4p5nlvrmxw66bh5qhie1w404 foreign key (ORDER_ID) references ORDER (ID);
alter table PAYMENT_INFORMATION add constraint FK6p98i38rg2ljjpd71d8ci3bcb foreign key (BILL_ID) references BILL_INFORMATION (ID);
