--liquibase formatted sql logicalFilePath:role.sql
INSERT INTO ROLE (NAME) VALUES("ROLE_WHOLESALER");
INSERT INTO ROLE (NAME) VALUES("ROLE_DISTRIBUTOR");
INSERT INTO ROLE (NAME) VALUES("ROLE_VISITOR");